### ISSUE TITLE
Node start error (java.lang.UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by ProfDD** [snowblossomcoin/snowblossom#100]
Win10 x64, Java 8
SnowBlossom 1.2.0

when run node.bat, got error:

 snowblossom.lib.db.rocksdb.JRocksDB <init> Loadng RocksDB with path node_db/mainnet
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\librocksdbjni7285975858024933511.dll

it said "DLL initial failed", What does that mean? What shall I do?
Then the node shutdown.... can't be used.

Thanks

**Comment by fireduck64** [comment]
duplicate of #32

**Comment by cluelessperson** [comment]
https://github.com/snowblossomcoin/snowblossom/wiki/FAQ#rocksdb-error
