### ISSUE TITLE
Combination Node/Pool uses all available ram

### ISSUE THREAD

**Issue by cluelessperson** [snowblossomcoin/snowblossom#106]
Seem very reliable, but seem to have used all the ram on this (low ram) machine, to the point that monitoring processes could not connect out.

**Comment by fireduck64** [comment]
If possible, run for a while and use jmap to create a heap dump.

**Comment by fireduck64** [comment]
Also, try running -Xmx option suitable to the machine. For example on a 2gb
os, try with -Xmx1g

**Comment by fireduck64** [comment]
closing until more information is presented
