### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by dystophia** [snowblossomcoin/snowblossom#128]
Node version: 1.4.0-dev, ubuntu 18.04, OpenJDK 1.8.0_181

Node outputs endless loop of this message:

Oct 23, 2018 9:31:35 PM snowblossom.node.PeerLink onNext
INFO: Requesting cluster for tx: 253a49fd6e80172cde898e8e3bcae2093a8c6bfc1eb94ceb77e4eea4b93693e8
Oct 23, 2018 9:31:35 PM snowblossom.node.PeerLink onNext
INFO: Requesting cluster for tx: 253a49fd6e80172cde898e8e3bcae2093a8c6bfc1eb94ceb77e4eea4b93693e8
Oct 23, 2018 9:31:35 PM snowblossom.node.PeerLink onNext
INFO: Requesting cluster for tx: 253a49fd6e80172cde898e8e3bcae2093a8c6bfc1eb94ceb77e4eea4b93693e8
Oct 23, 2018 9:31:35 PM snowblossom.node.PeerLink onNext

After restarting it was fine again. Let me know if you need more information.

**Comment by fireduck64** [comment]
That isn't quite a crash, but it isn't right either.

**Comment by dystophia** [comment]
It was not accepting new blocks and was consuming 100% CPU, but you are right, it was still running.

**Comment by fireduck64** [comment]
Oh, that is severe and clearly shouldn't happen.
