### ISSUE TITLE
Submitwork erroe while using arktika

### ISSUE THREAD

**Issue by jq8778** [snowblossomcoin/snowblossom#149]
I have tried to config arktika and it seems working perfectly except when it uses submitWork function.

It has throwed the following info:
[2018-11-14 14:51:15] WARNING snowblossom.miner.LayerWorkThread run Error: java.lang.RuntimeException: oh noes
java.lang.RuntimeException: oh noes
        at snowblossom.miner.FieldSourceComposit.bulkRead(FieldSourceComposit.java:51)
        at snowblossom.miner.FieldSource.readWord(FieldSource.java:32)
        at snowblossom.miner.LayerWorkThread.submitWork(LayerWorkThread.java:152)
        at snowblossom.miner.BatchLayerWorkThread.processPw(BatchLayerWorkThread.java:104)
        at snowblossom.miner.BatchLayerWorkThread.runPass(BatchLayerWorkThread.java:86)
        at snowblossom.miner.LayerWorkThread.run(LayerWorkThread.java:185)

The config file of the host which use to host snowfiled is 
"""
mine_to_address=myaddress

pool_host=snowblossom.hamster.science
log_config_file=configs/logging.properties
layer_count=1

layer_0_type=file
layer_0_path=/mnt/tmp
layer_0_threads=0

memfield=false
selected_field=7
"""

The config file of the host which is used to mining is :
"""
mine_to_address=myaddress
log_config_file=configs/logging.properties
pool_host=snowblossom.hamster.science

layer_count=4

layer_0_type=file
layer_0_path=/mnt/tmp
layer_0_threads=8

layer_1_type=remote
layer_1_range=0,47
layer_1_threads=8
layer_1_host=10.10.0.1

layer_2_type=remote
layer_2_range=48,96
layer_2_threads=8
layer_2_host=10.10.0.2

layer_3_type=remote
layer_3_range=97,127
layer_3_threads=8
layer_3_host=10.10.0.3

memfield=false
selected_field=7
"""

Cant figure out whats going on, can anyone help?

**Comment by fireduck64** [comment]
Try swapping layer 0 and 3 on the miner. The file layer should be last.

**Comment by fireduck64** [comment]
Sorry that error was not helpful I'm not sure why I didn't put something better in. That error means that it's trying to read from a chunk that isn't in any of the layers.

**Comment by jq8778** [comment]
You are right, i have moved it to layer 3 but still get the same error.
![00a](https://user-images.githubusercontent.com/18402588/48502010-897a9880-e879-11e8-93a8-4a029df14c8f.png)

**Comment by fireduck64** [comment]
When it starts up, it should print a big block of which field is in which layer. It should look like this:

INFO: {0=0, 1=0, 2=0, 3=0, 4=0, 5=0, 6=0, 7=0, 8=0, 9=0, 10=0, 11=0, 12=0, 13=0, 14=0, 15=0, 16=0, 17=0, 18=0, 19=0, 20=0, 21=0, 22=0, 23=0, 24=0, 25=0, 26=0, 27=0, 28=0, 29=0, 30=0, 31=0, 32=0, 33=0, 34=0, 35=0, 36=0, 37=0, 38=0, 39=0, 40=0, 41=0, 42=0, 43=0, 44=0, 45=0, 46=0, 47=0, 48=0, 49=0, 50=0, 51=0, 52=0, 53=0, 54=0, 55=0, 56=0, 57=0, 58=0, 59=0, 60=0, 61=0, 62=0, 63=0, 64=0, 65=0, 66=0, 67=0, 68=0, 69=0, 70=0, 71=0, 72=0, 73=0, 74=0, 75=0, 76=0, 77=0, 78=0, 79=0, 80=0, 81=0, 82=0, 83=0, 84=0, 85=0, 86=0, 87=0, 88=0, 89=0, 90=0, 91=0, 92=0, 93=0, 94=0, 95=0, 96=0, 97=0, 98=0, 99=0, 100=0, 101=0, 102=0, 103=0, 104=0, 105=0, 106=0, 107=0, 108=0, 109=0, 110=0, 111=0, 112=0, 113=0, 114=0, 115=0, 116=0, 117=0, 118=0, 119=0, 120=0, 121=0, 122=0, 123=0, 124=0, 125=0, 126=0, 127=0}

What does that show for you?  Are there any missing numbers?

**Comment by fireduck64** [comment]
Can you update to latest version in github and try again?  I've improved the error message.

**Comment by jq8778** [comment]
will try...

**Comment by jq8778** [comment]
It gives following info:

WARNING: Error: java.lang.RuntimeException: Unable to find field for chunk: 5
java.lang.RuntimeException: Unable to find field for chunk: 5
        at snowblossom.miner.FieldSourceComposit.bulkRead(FieldSourceComposit.java:51)
        at snowblossom.miner.FieldSource.readWord(FieldSource.java:32)
        at snowblossom.miner.LayerWorkThread.submitWork(LayerWorkThread.java:152)
        at snowblossom.miner.BatchLayerWorkThread.processPw(BatchLayerWorkThread.java:104)
        at snowblossom.miner.BatchLayerWorkThread.runPass(BatchLayerWorkThread.java:86)
        at snowblossom.miner.LayerWorkThread.run(LayerWorkThread.java:185)

**Comment by jq8778** [comment]
BTW, before this error it seems miner has given the hash result:
INFO: Found passable solution: 0000022e1bc1ac1ea22264363406836947ff5a2a640fffce84cf9d70ecfffd50
Hope this can help u figure out whats the problem...
