### ISSUE TITLE
Delete old rocksdb database logfiles

### ISSUE THREAD

**Issue by hamsterscience** [snowblossomcoin/snowblossom#161]
Old logfiles for the database node and pool (LOG.old*) are not restricted in growth or deleted. In particular the log files for the node db can grow to several gigabytes after a few months.

Suggestion: Limit size via config files or delete after x days.

Workaround: Delete old files via cron job

**Comment by fireduck64** [comment]
I've never seen them grow that big.  How many are you seeing?

The probable solution is probable to change this option:
https://jar-download.com/javaDoc/org.rocksdb/rocksdbjni/5.14.2/org/rocksdb/Options.html#setKeepLogFileNum(long)

**Comment by fireduck64** [comment]
6317e65cf4765af731d46c9ad4e9f438e0ee5963
