### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [snowblossomcoin/snowblossom#171]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by fireduck64** [comment]
Updated to 1.65 with ac0f49c65f935ba9b5d573fc7048ee44b1f7580b

As for the spongecastle, that is needed or used on android since android of course comes with its own (out of date) version of bouncycastle so you can't just load in a new bouncycastle.  This renaming all the classes to produce spongecastle.  Unfortunately that is getting increasingly out of date as well.

Added a warning in ac0f49c65f935ba9b5d573fc7048ee44b1f7580b

**Comment by Neustradamus** [comment]
@fireduck64: Thanks a lot!

**Comment by Neustradamus** [comment]
@fireduck64: Always here :/
Can you look?
- https://github.com/snowblossomcoin/snowblossom/search?q=spongycastle&unscoped_q=spongycastle

**Comment by Neustradamus** [comment]
@fireduck64: It is not needed!

Currently Bouncy Castle last version is 1.65 and Spongy Castle last version is 1.58.
Spongy Castle is a fork of Bouncy Castle.
Please look previous links :)

Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle because the project is dead.

You can see discussion "34" in https://github.com/rtyley/spongycastle/issues.

**Comment by fireduck64** [comment]
ok, cool.  It has been a while since I messed with the android side.

**Comment by Neustradamus** [comment]
@fireduck64: Thanks for Bouncy Castle 1.68 update!
But there is always one old part here, can you look?
- https://github.com/snowblossomcoin/snowblossom/search?q=spongycastle&unscoped_q=spongycastle

**Comment by fireduck64** [comment]
I am working on this.  Right now am blocked by:
https://github.com/bitcoinj/bitcoinj/issues/2076

**Comment by Neustradamus** [comment]
@fireduck64: Solved in bitcoinj now :)

**Comment by fireduck64** [comment]
But not yet in the maven bitcoinj artifact.

**Comment by Neustradamus** [comment]
@fireduck64: Can you remove latest part of spongycastle?
- https://github.com/snowblossomcoin/snowblossom/search?q=spongycastle&unscoped_q=spongycastle

Can you update bouncycastle to 1.69?

**Comment by fireduck64** [comment]
Handled with 6ae15030afc930d879be1274d5184b5493d7dd90

**Comment by Neustradamus** [comment]
@fireduck64: Good job, thanks a lot!
