### ISSUE TITLE
JSON output format

### ISSUE THREAD

**Issue by fireduck64** [snowblossomcoin/snowblossom#200]
The JSON outputs from the rpc calls return a lot of things in somewhat useless base64 encoding.

People might now be depending on that, but we can add other fields that are encoded properly for addresses and hashes.

The pattern should be use proto libraries to make the json (as we do now) and pass that to something that will read fields and write them as new fields converted.

**Comment by Sykh** [comment]
Found so far
get_block -> block.transactions.txHash is base64 byte, not the needed hex for get_transaction
get_transaction -> returns recipientSpecHash instead of a readable now address
there are probably more :)
