### ISSUE TITLE
Make client functions use default config locations

### ISSUE THREAD

**Issue by cluelessperson** [snowblossomcoin/snowblossom#29]
Preferably automatically use:

* Windows: `%applicationdata%/SnowBlossom/configs/client.conf`  ?
* Linux: `~/.snowblossom/configs/client.conf` OR `~/configs/client.conf`
* Mac: ?

**Comment by fireduck64** [comment]
Yeah, can do

**Comment by cluelessperson** [comment]
Setting this to high priority as it effects user experience.
