### ISSUE TITLE
java heap about twice as large as it should be

### ISSUE THREAD

**Issue by fireduck64** [snowblossomcoin/snowblossom#36]
For example, memfield on 4gb stoat file needs -Xmx10g to run.

**Comment by fireduck64** [comment]
Seems to only be a problem on windows.  Strange.

**Comment by fireduck64** [comment]
@tster123 hoping you wouldn't mind doing a windows heap dump and see what is going on here.

I wouldn't be surprised by it being terrible code in SnowMerkleProof, which really needs a refactor.

**Comment by tster123** [comment]
It seems like this is caused by some kind of issue with the G1 garbage collector failing to collect.   The behavior goes away if I use -XX:+UseConcMarkSweepGC.   Sadly, that also seems to reduce performance...

**Comment by cluelessperson** [comment]
Nice find @tster123

The performance loss is minimal for me.

**Comment by tster123** [comment]
I didn't do very extensive performance testing.  And at the time I didn't realize there was significant warm-up time while the in-memory snowfield gets populated, so I probably was just seeing the effect of not running the miner long enough for the throughput to even out.
