### ISSUE TITLE
Improvement: Deterministic wallets?

### ISSUE THREAD

**Issue by fireduck64** [snowblossomcoin/snowblossom#48]
So we can do deterministic wallets bip39 style from a seed and HD derivation like other things for EC keys. 
That is no problem.

It would be nice to do it for non-EC keys as well, but the part with the xpub deriving addresses without the need of the private key is EC-only magic.  But we don't really need that, we could do derivable non-EC keys with using the seed to feed into a deterministic PRNG and then have that used as the SecureRandom to generate other types of keys.

There are problems that probably make this a bad idea:
- If the key generation does any sort of floating point or per-platform/environment optimization it could generate different addresses on different machines/platforms/environments.
- If the key generation algorithm changes in any ways, we will almost certainly generate different keys.

This isn't the sort of thing we can screw around on.  Probably a bad idea.

**Comment by tynes** [comment]
I would really like to see this as the UX around coins that don't support some type of bip39 style key derivation isn't always the best. It sounds like you know about this: https://github.com/satoshilabs/slips/blob/master/slip-0010.md

**Comment by fireduck64** [comment]
@tynes I understand completely.  I really enjoy seed based deterministic wallets and use them almost exclusively in other coins.

I could make EC only wallets that support deterministic generation but then how people save a wallet depends on what time of wallet it is and I concerned about that sort of confusion.

It is absolutely still on my mine.

**Comment by fireduck64** [comment]
Bam.
