### ISSUE TITLE
Pool Miner - Work Submit Status - Stats in general

### ISSUE THREAD

**Issue by cXplexus** [snowblossomcoin/snowblossom#71]
When pool miner submits a share add a counter to how many shares have been accepted or rejected.

1253/1253 or 1222/1253.

This way we can get a running time on how many shares have been accepted over time.
It's a bit difficult to see stats

**Comment by fireduck64** [comment]
That is entirely reasonable

**Comment by seanspotatobusiness** [comment]
I would like it if it also said explicitly when shares are accepted or rejected. If it just have a number like 1222/1253 I wouldn't know what it was referring to! Thanks.

**Comment by cXplexus** [comment]
It would be nice to get this on the pool side as well. I know that is not on you. I'm just trying to get an estimate on if all these Work Submitted: True   submissions are actually going to a block or not. It appears snowday is hitting blocks on the explorer. But it seems nothing.

**Comment by cXplexus** [comment]
Sean, 

It does say that. Work Submitted: True. You'll see it if you watch it long enough.
Estimate it by time to share

**Comment by seanspotatobusiness** [comment]
Oh, okay. Thanks!

**Comment by cXplexus** [comment]
No Problem!

**Comment by fireduck64** [comment]
Woo INFO: Shares: 4 (rejected 0) (blocks 1)

**Comment by cXplexus** [comment]
Awesome!
