### ISSUE TITLE
CMD window titles: suggest e.g. TITLE Snowblossom node in node.bat

### ISSUE THREAD

**Issue by seanspotatobusiness** [snowblossomcoin/snowblossom#72]
Currently when the .bat files are run the resulting CMD window has C:\Windows\System32\cmd.exe in the titlebar which is useless for indentification when you have multiple CMD windows open (I have three windows open pertaining to Snowblossom and two unrelated ones). This would be easy to address by putting something like:

TITLE Snowblossom node
and
TITLE Snowblossom client

at the very top of the existing node.bat and client.bat etc etc. I've edited my own .bat files so that the windows are easier to identify but it would be nicer for end users if the ones downloaded from Github were like this.

**Comment by fireduck64** [comment]
This is a great idea
