### ISSUE TITLE
sample1-install-node-systemd-service-latest-release.sh fails on Ubuntu 16.04 for snowblossom-1.1.0

### ISSUE THREAD

**Issue by iSnow** [snowblossomcoin/snowblossom#84]
I had an older version of snowblossom compiled and installed from source and tried to install `sample1-install-node-systemd-service-latest-release.sh` via `https://github.com/snowblossomcoin/snowblossom/blob/master/example/scripts/sample1-install-node-systemd-service-latest-release.sh

after extracting the zip file in /var/snowblossom the script fails - most likely in line 32:"ln -sf "$snowblossom_home/systemd/snowblossom-node.service" /etc/systemd/system/"

Here's the output:

    replace snowblossom-1.1.0/configs/client.conf? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
    replace snowblossom-1.1.0/configs/pool-miner.conf? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
    replace snowblossom-1.1.0/configs/logging.properties? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
    replace snowblossom-1.1.0/configs/miner.conf? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
    replace snowblossom-1.1.0/configs/node.conf? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
       creating: snowblossom-1.1.0/wallet/
      inflating: snowblossom-1.1.0/wallet/readme.txt  
      inflating: snowblossom-1.1.0/node.sh  
       creating: snowblossom-1.1.0/snow/
      inflating: snowblossom-1.1.0/snow/readme.txt  
      inflating: snowblossom-1.1.0/send.bat  
      inflating: snowblossom-1.1.0/pool-miner.sh  
      inflating: snowblossom-1.1.0/SnowBlossomMiner_deploy.jar  
    Failed to execute operation: Too many levels of symbolic links

copying the service definition files from `systemd/` and then starting manually still seems to work.

**Comment by cluelessperson** [comment]
Thanks for opening the issue.  Looking now.

1. I notice you're getting replacement questions, looks like a rerun
2. works on debian.
3. testing ubuntu next

**Comment by cluelessperson** [comment]
3. Tested on Ubuntu 18.04, works
4. Testing on Ubuntu 16.04...

**Comment by cluelessperson** [comment]
Can you provide me a current file tree?

`tree /var/snowblossom`

**Comment by iSnow** [comment]
sure, here goes. 

[tree.txt](https://github.com/snowblossomcoin/snowblossom/files/2110181/tree.txt)

**Comment by cluelessperson** [comment]
I spoke too soon.

**Comment by cluelessperson** [comment]
should be fixed with change.
